coarse:
  model:
    deca_class: ExpDECA
    expression_backbone: deca_clone
    max_epochs: 30
    val_check_interval: 0.2
    test_vis_frequency: 1
    val_vis_frequency: 200
    train_vis_frequency: 1000
    mode: coarse
    resume_training: false
    useSeg: gt
    background_from_input: false
    use_landmarks: false
    use_mediapipe_landmarks: true
    useWlmk: true
    lmk_weight: 1
    lmk_weight_mp: 32.0
    eyed: 0.5
    lipd: 0.5
    eyed_mp: 36.0
    lipd_mp: 36.0
    idw: 0
    exp_reg: 0.0001
    shape_reg: 0.0001
    tex_reg: 1.0e-05
    light_reg: 12
    use_photometric: true
    photow: 2.0
    shape_constrain_type: exchange
    expression_constrain_type: none
    expression_constrain_use_jaw_pose: true
    expression_constrain_use_global_pose: false
    use_geometric_losses_expression_exchange: false
    exp_deca_global_pose: false
    exp_deca_jaw_pose: false
    use_emonet_loss: true
    use_emonet_feat_1: false
    use_emonet_feat_2: true
    use_emonet_valence: false
    use_emonet_arousal: false
    use_emonet_expression: false
    use_emonet_combined: false
    emonet_weight: 1.0
    use_gt_emotion_loss: false
    gt_emotion_reg: 0.0
    n_shape: 100
    n_tex: 50
    n_exp: 50
    n_pose: 6
    n_cam: 3
    n_light: 27
    n_identity: 512
    n_dlatent: 512
    n_detail: 128
    image_size: 224
    uv_size: 256
    neural_renderer: false
    tex_type: BFM
    lipread_loss:
      lipread_loss: mse_loss
      weight: 20.0
      use_as_loss: true
      load: false
    emonet_model_path: ''
    emo_feat_loss: mse_loss
    photometric_normalization: mean
    use_mouth_corner_distance: false
    use_mouth_corner_distance_mediapipe: true
    use_eye_distance: false
    use_eye_distance_mediapipe: true
    use_lip_distance: false
    use_lip_distance_mediapipe: true
    zero_out_last_enc_layer: false
    use_texture: false
  learning:
    batch_size_train: 8
    batch_size_test: 8
    batch_size_val: 8
    train_K: 1
    val_K: 1
    test_K: 1
  inout:
    output_dir: . # placeholder
detail:
  model:
    deca_class: ExpDECA
    expression_backbone: deca_clone
    exp_deca_global_pose: false
    exp_deca_jaw_pose: false
    max_epochs: 12
    val_check_interval: 0.2
    test_vis_frequency: 1
    val_vis_frequency: 200
    train_vis_frequency: 1000
    train_coarse: false
    useSeg: gt
    background_from_input: true
    detail_constrain_type: exchange
    expression_constrain_type: none
    expression_constrain_use_jaw_pose: true
    expression_constrain_use_global_pose: false
    use_geometric_losses_expression_exchange: false
    mode: detail
    resume_training: false
    lmk_weight: 1
    eyed: 0.5
    lipd: 0.5
    use_photometric: true
    photow: 2
    idw: 0
    use_landmarks: true
    useWlmk: true
    shape_reg: 0.0001
    exp_reg: 0.0001
    tex_reg: 0.0001
    light_reg: 12
    useConstraint: true
    mrfwr: 0.05
    zregw: 0.005
    zdiffw: 0.005
    zsymw: 0.005
    consr: 1
    sfsw:
    - 5
    - 0
    - 0
    - 0
    use_detail_l1: true
    use_detail_mrf: true
    use_detailed_photo: false
    use_emonet_loss: false
    use_emonet_feat_1: false
    use_emonet_feat_2: false
    use_emonet_valence: false
    use_emonet_arousal: false
    use_emonet_expression: false
    use_emonet_combined: false
    emonet_weight: 0.0015
    use_gt_emotion_loss: false
    gt_emotion_reg: 0.0
    n_shape: 100
    n_tex: 50
    n_exp: 50
    n_pose: 6
    n_cam: 3
    n_light: 27
    n_identity: 512
    n_dlatent: 512
    n_detail: 128
    image_size: 224
    uv_size: 256
    neural_renderer: false
    tex_type: BFM
    emonet_model_path: ''
    use_texture: false
  learning:
    batch_size_train: 8
    batch_size_test: 8
    batch_size_val: 8
    train_K: 2
    val_K: 1
    test_K: 1
  inout:
    output_dir: . # placeholder
